### ISSUE TITLE
Add ReadProcessMemory

### ISSUE THREAD

**Issue by CoolOppo** [AllenDang/w32#37]

**Comment by ahmetabdi** [comment]
:+1:

**Comment by Xackery** [comment]
I know a year old, but, 

I added it on my fork, including an example: https://github.com/Xackery/w32/blob/master/example/readprocessmemory.go

There's also a WriteProcessMemory method. https://github.com/Xackery/w32/blob/master/example/writeprocessmemory.go

**Comment by CoolOppo** [comment]
@Xackery make a pull request!

**Comment by Xackery** [comment]
@CoolOppo  already did. https://github.com/AllenDang/w32/pull/50

**Comment by ahmetabdi** [comment]
Nice :+1:

**Comment by xackery** [comment]
@CoolOppo if you want me to revise this or adjust (wow this was 5 years ago+ now) i'm happy to. :) would love to extend this w32 package.
