### ISSUE TITLE
Tutorial for integrating with visual studio Winforms GUI builder 

### ISSUE THREAD

**Issue by Immortalin** [AllenDang/w32#47]
Hi, can you do a tutorial on using this with the Winforms GUI builder in visual studio?

**Comment by Xackery** [comment]
This is more a wrapper for typical win32 DLL calls than any GUI-specific tutorials, especially with Visual Studio's builder.

Alan has another repo https://github.com/AllenDang/gform that goes more into windows GUI related stuff.
