### ISSUE TITLE
mobiles

### ISSUE THREAD

**Issue by joeblew99** [AllenDang/w32#70]
This is a bit out there but did you even try windows Mobile using gomobile ?

I use gomobile and its opengl support to run apps on all desktops and mobiles, but am investigating supporting microsoft mobiles.

SO i figured its worth asking.

**Comment by AllenDang** [comment]
No, I haven't try windows mobile using gomobile.

**Comment by joeblew99** [comment]
yeah i dont think its possible at all yet. golang team dont support it.
will close...
